<?php

namespace ContainerQ84tgso;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XnzgXxUService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.XnzgXxU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XnzgXxU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'roleAdmin' => ['privates', '.errored..service_locator.XnzgXxU.App\\Entity\\RoleAdmin', NULL, 'Cannot autowire service ".service_locator.XnzgXxU": it needs an instance of "App\\Entity\\RoleAdmin" but this type has been excluded in "config/services.yaml".'],
        ], [
            'roleAdmin' => 'App\\Entity\\RoleAdmin',
        ]);
    }
}
