<?php

namespace ContainerQ84tgso;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AdminType' shared autowired service.
     *
     * @return \App\Form\AdminType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AdminType'] = new \App\Form\AdminType();
    }
}
