<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ84tgso\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ84tgso/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQ84tgso.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQ84tgso\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQ84tgso\App_KernelProdContainer([
    'container.build_hash' => 'Q84tgso',
    'container.build_id' => '647bc378',
    'container.build_time' => 1693405466,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ84tgso');
