<?php

namespace ContainerOwwkpxr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleAdminService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GByJmOW.App\Entity\RoleAdmin' shared service.
     *
     * @return \App\Entity\RoleAdmin
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.GByJmOW": it needs an instance of "App\\Entity\\RoleAdmin" but this type has been excluded in "config/services.yaml".');
    }
}
