<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKDCIIPV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKDCIIPV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKDCIIPV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKDCIIPV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKDCIIPV\App_KernelDevDebugContainer([
    'container.build_hash' => 'KDCIIPV',
    'container.build_id' => 'b624d1ea',
    'container.build_time' => 1693457691,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKDCIIPV');
