<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXIP2FcU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXIP2FcU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXIP2FcU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXIP2FcU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXIP2FcU\App_KernelDevDebugContainer([
    'container.build_hash' => 'XIP2FcU',
    'container.build_id' => '0df28f8e',
    'container.build_time' => 1693458341,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXIP2FcU');
